- A "not too old" compiler is required on FreeBSD < 10;
- Mark BROKEN on FreeBSD < 10 and i386:
/usr/local/lib/libsodium.so: undefined reference to `__stack_chk_fail_local'

Reported by:	pkg-fallout


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@346315 35697150-7ecd-e111-bb59-0022644237b5