Mark broken: does not compile
tgif.c: In function 'rb_ext_Tgif_out':
tgif.c:50: error: 'OpenFile' undeclared (first use in this function)
tgif.c:50: error: (Each undeclared identifier is reported only once
tgif.c:50: error: for each function it appears in.)
tgif.c:50: error: 'fptr' undeclared (first use in this function)

Reported by:	pkg-fallout since august 2013


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@344010 35697150-7ecd-e111-bb59-0022644237b5