Mark as broken: Fails to build
On 8 and 9:
cc -O2 -pipe -fno-strict-aliasing -D_BSD_SOURCE -DLIBNET_BSDISH_OS -DLIBNET_BSD_BYTE_SWAP -DHAVE_SOCKADDR_SA_LEN -DLIBNET_LIL_ENDIAN -DDSNIFF_LIBDIR=\"/usr/local/lib/\" -I. -I/usr/local/include -I/usr/include/pcap -DLIBNET_BSDISH_OS -DLIBNET_BSD_BYTE_SWAP -DHAVE_SOCKADDR_SA_LEN -DLIBNET_LIL_ENDIAN -I/usr/local/include/libnet10   -I/usr/local/include -c ./nfs_prot.c
./nfs_prot.c:6:22: error: nfs_prot.h: No such file or directory
./nfs_prot.c:10: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'xdr_nfsstat'
./nfs_prot.c:19: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'xdr_ftype'

On 10 and head:
/usr/local/lib/libnids.a(libnids.o): In function `gen_ip_frag_proc':
libnids.c:(.text+0x1060): undefined reference to `ip_fast_csum'
/usr/local/lib/libnids.a(libnids.o): In function `gen_ip_proc':
libnids.c:(.text+0x1201): undefined reference to `my_udp_check'
/usr/local/lib/libnids.a(tcp.o): In function `process_tcp':
tcp.c:(.text+0x5b4): undefined reference to `my_tcp_check'
/usr/local/lib/libnids.a(tcp.o): In function `process_icmp':
tcp.c:(.text+0x12f6): undefined reference to `ip_compute_csum'
cc: error: linker command failed with exit code 1 (use -v to see invocation)
*** Error code 1

Reported by:	pkg-fallout since august 2013
With hat:	portmgr


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@342134 35697150-7ecd-e111-bb59-0022644237b5