databases/gnats4: Fix build failure on FreeBSD 10
gnats/gnats.h contains its own prototypes of asprintf() and vasprintf()
which conflict with the system ones:

In file included from edit.c:21:
./gnats.h:140:12: error: conflicting types for 'asprintf'
extern int asprintf (char **buf, const char *fmt, ...);
          ^
/usr/include/stdio.h:396:6: note: previous declaration is here
int      asprintf(char **, const char *, ...) __printflike(2, 3);

Just remove the prototypes from gnats.h.

Reported by:    miwi@


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@320441 35697150-7ecd-e111-bb59-0022644237b5