- Still broken as it depends on MD2 and md2.h still.
./generic/md2.c:31:10: fatal error: 'md2.h' file not found

With hat:	portmgr


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@350800 35697150-7ecd-e111-bb59-0022644237b5