Mark broken again, does not build cc -I. -I. -DUSE_PPP -DUSE_MS_DNS -O2 -pipe -fno-strict-aliasing -c ./ppp/auth.c In file included from ./ppp/auth.c:56: ./ppp/pppd.h:107: error: conflicting types for 'output' ./ppp.p:13: error: previous declaration of 'output' was here *** Error code 1
Reported by:	pkg-fallout (still since at least august 2013)


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@349465 35697150-7ecd-e111-bb59-0022644237b5