Fix some files unreadable by regular users,  this causes errors like:
  File "/usr/local/lib/python2.7/site-packages/pkg_resources.py", line 1514, in _get
    with open(path, 'rb') as stream:
IOError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/site-packages/WebError-0.10.3-py2.7.egg-info/entry_points.txt'

While here, modernize a bit


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@365737 35697150-7ecd-e111-bb59-0022644237b5