Mark broken: fails to build
error CS1705: Assembly `MonoDevelop.Core, Version=2.6.0.0, Culture=neutral, PublicKeyToken=null' references `Mono.Addins, Version=1.0.0.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756' which has a higher version number than imported assembly `Mono.Addins, Version=0.6.0.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756'
Compilation failed: 1 error(s), 0 warnings
gmake[2]: *** [../build/MonoDevelop.Database.Sql.dll] Error 1

Reported by:	pkg-fallout since september 2013
With hat:	portmgr


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@343311 35697150-7ecd-e111-bb59-0022644237b5